-- ============================================
-- NEXUS MIGRATION 003
-- Intelligence Integration
-- Attribution UTM, Conversation Outcomes,
-- Auto-Learning Insights, Conversion Events
-- ============================================

-- ─── 1. UTM Attribution on contacts ──────────────────────────────────────────
-- First-touch attribution: the first campaign that generated the lead gets credit
-- Never overwritten — first-touch model

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS utm_source       TEXT,
  ADD COLUMN IF NOT EXISTS utm_medium       TEXT,
  ADD COLUMN IF NOT EXISTS utm_campaign     TEXT,
  ADD COLUMN IF NOT EXISTS utm_content      TEXT,
  ADD COLUMN IF NOT EXISTS utm_term         TEXT,
  ADD COLUMN IF NOT EXISTS utm_ad_id        TEXT,
  ADD COLUMN IF NOT EXISTS utm_adset_id     TEXT,
  ADD COLUMN IF NOT EXISTS utm_campaign_id  TEXT,
  ADD COLUMN IF NOT EXISTS utm_channel      TEXT,   -- 'meta_paid' | 'google_paid' | 'organic' | 'direct' | 'whatsapp_direct'
  ADD COLUMN IF NOT EXISTS attributed_at    TIMESTAMPTZ;

-- ─── 2. Outcome + Attribution snapshot on conversations ───────────────────────
-- Attribution snapshot: copied from contact at conversation start
-- Outcome: recorded by agent when closing the conversation

ALTER TABLE conversations
  -- Attribution snapshot (immutable after creation)
  ADD COLUMN IF NOT EXISTS attr_source      TEXT,
  ADD COLUMN IF NOT EXISTS attr_medium      TEXT,
  ADD COLUMN IF NOT EXISTS attr_campaign    TEXT,
  ADD COLUMN IF NOT EXISTS attr_campaign_id TEXT,
  ADD COLUMN IF NOT EXISTS attr_ad_id       TEXT,
  ADD COLUMN IF NOT EXISTS attr_channel     TEXT,
  -- Outcome fields
  ADD COLUMN IF NOT EXISTS outcome          TEXT CHECK (outcome IN ('converted', 'lost', 'problem', NULL)),
  ADD COLUMN IF NOT EXISTS outcome_value    NUMERIC(12,2),
  ADD COLUMN IF NOT EXISTS outcome_currency TEXT DEFAULT 'BRL',
  ADD COLUMN IF NOT EXISTS outcome_reason   TEXT,
  ADD COLUMN IF NOT EXISTS outcome_product  TEXT,
  ADD COLUMN IF NOT EXISTS outcome_at       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS outcome_by       UUID REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_outcome
  ON conversations(org_id, outcome) WHERE outcome IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_attr_channel
  ON conversations(org_id, attr_channel) WHERE attr_channel IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_conversations_attr_campaign
  ON conversations(org_id, attr_campaign_id) WHERE attr_campaign_id IS NOT NULL;

-- ─── 3. Conversation insights (auto-learning engine) ──────────────────────────
-- Generated by Claude after each closed conversation
-- Best patterns are injected into the RAG knowledge base

CREATE TABLE IF NOT EXISTS conversation_insights (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  sector_id       UUID REFERENCES sectors(id) ON DELETE SET NULL,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,

  -- What happened
  outcome         TEXT NOT NULL CHECK (outcome IN ('converted', 'lost', 'problem')),
  outcome_value   NUMERIC(12,2),
  attr_channel    TEXT,
  attr_campaign   TEXT,

  -- Structured insight extracted by Claude
  insight_type    TEXT NOT NULL CHECK (insight_type IN (
    'winning_pattern',     -- approach that led to conversion
    'losing_pattern',      -- approach that led to loss
    'key_phrase',          -- effective phrase or message
    'objection_handled',   -- objection successfully addressed
    'turning_point',       -- moment conversation changed direction
    'playbook_step'        -- actionable step to replicate
  )),
  title           TEXT    NOT NULL,
  description     TEXT    NOT NULL,
  example_quote   TEXT,              -- exact quote from conversation
  playbook        TEXT,              -- "how to replicate this"
  tags            TEXT[]  DEFAULT '{}',
  confidence      NUMERIC(3,2)       CHECK (confidence BETWEEN 0 AND 1),

  -- AI metadata
  ai_model        TEXT,
  ai_tokens_used  INTEGER,

  -- RAG injection status
  injected_to_rag   BOOLEAN   DEFAULT FALSE,
  rag_document_id   UUID      REFERENCES knowledge_documents(id) ON DELETE SET NULL,

  is_active       BOOLEAN   DEFAULT TRUE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_insights_org_created
  ON conversation_insights(org_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_insights_sector_type
  ON conversation_insights(sector_id, insight_type) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_insights_outcome
  ON conversation_insights(org_id, outcome, confidence DESC);

CREATE INDEX IF NOT EXISTS idx_insights_pending_rag
  ON conversation_insights(org_id)
  WHERE injected_to_rag = FALSE AND outcome = 'converted' AND confidence >= 0.7;

CREATE TRIGGER trg_insights_updated_at
  BEFORE UPDATE ON conversation_insights
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─── 4. Conversation analysis jobs ───────────────────────────────────────────
-- Tracks background jobs that analyze closed conversations
-- One job per conversation, deduplicated

CREATE TABLE IF NOT EXISTS conversation_analysis_jobs (
  id              UUID    PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID    NOT NULL,
  conversation_id UUID    NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  status          TEXT    DEFAULT 'pending'
                  CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'skipped')),
  triggered_at    TIMESTAMPTZ DEFAULT NOW(),
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  insights_count  INTEGER DEFAULT 0,
  error_message   TEXT,
  retry_count     INTEGER DEFAULT 0,
  UNIQUE(conversation_id)
);

CREATE INDEX IF NOT EXISTS idx_analysis_jobs_pending
  ON conversation_analysis_jobs(org_id, status, triggered_at)
  WHERE status IN ('pending', 'failed');

-- ─── 5. Conversion events (for CAPI reporting to Meta/Google) ────────────────
-- Created when an agent marks a conversation as 'converted'
-- Intelligence reads these and sends to Meta Conversion API / Google Ads

CREATE TABLE IF NOT EXISTS conversion_events (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  contact_id      UUID NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,

  -- Conversion data
  event_type      TEXT DEFAULT 'Purchase'
                  CHECK (event_type IN ('Purchase', 'Lead', 'CompleteRegistration')),
  value           NUMERIC(12,2),
  currency        TEXT DEFAULT 'BRL',
  product_name    TEXT,

  -- Attribution snapshot (from conversation)
  attr_source     TEXT,
  attr_medium     TEXT,
  attr_campaign   TEXT,
  attr_campaign_id TEXT,
  attr_ad_id      TEXT,
  attr_channel    TEXT,

  -- Contact data for matching (hashed by Intelligence before sending)
  contact_wa_id   TEXT,
  contact_phone   TEXT,
  contact_email   TEXT,

  -- Sending status — Meta CAPI
  meta_status     TEXT DEFAULT 'pending'
                  CHECK (meta_status IN ('pending', 'sent', 'failed', 'not_applicable')),
  meta_sent_at    TIMESTAMPTZ,
  meta_event_id   TEXT,   -- returned by Meta
  meta_error      TEXT,

  -- Sending status — Google Ads
  google_status   TEXT DEFAULT 'pending'
                  CHECK (google_status IN ('pending', 'sent', 'failed', 'not_applicable')),
  google_sent_at  TIMESTAMPTZ,
  google_error    TEXT,

  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversions_org
  ON conversion_events(org_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversions_pending_meta
  ON conversion_events(org_id, meta_status)
  WHERE meta_status = 'pending';

CREATE INDEX IF NOT EXISTS idx_conversions_contact
  ON conversion_events(contact_id);

CREATE TRIGGER trg_conversions_updated_at
  BEFORE UPDATE ON conversion_events
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─── 6. Pending attributions ─────────────────────────────────────────────────
-- Stores UTM data for contacts that haven't messaged yet
-- Applied when they send their first message

CREATE TABLE IF NOT EXISTS pending_attributions (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  wa_id           TEXT NOT NULL,
  utm_source      TEXT,
  utm_medium      TEXT,
  utm_campaign    TEXT,
  utm_content     TEXT,
  utm_term        TEXT,
  utm_ad_id       TEXT,
  utm_adset_id    TEXT,
  utm_campaign_id TEXT,
  utm_channel     TEXT,
  received_at     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(org_id, wa_id)
);

CREATE INDEX IF NOT EXISTS idx_pending_attr_lookup
  ON pending_attributions(org_id, wa_id);

-- API key for Intelligence platform integration
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS nexus_api_key TEXT UNIQUE;

-- ─── 6b. source_type on knowledge_documents ──────────────────────────────────
-- Distinguishes human-uploaded docs from auto-generated insights

ALTER TABLE knowledge_documents
  ADD COLUMN IF NOT EXISTS source_type TEXT
    DEFAULT 'manual'
    CHECK (source_type IN ('manual', 'auto_insight', 'playbook'));

-- ─── 7. RLS Policies ──────────────────────────────────────────────────────────

ALTER TABLE conversation_insights ENABLE ROW LEVEL SECURITY;
CREATE POLICY "insights_org_isolation" ON conversation_insights
  FOR ALL USING (org_id = get_user_org_id());

ALTER TABLE conversation_analysis_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "analysis_jobs_org_isolation" ON conversation_analysis_jobs
  FOR ALL USING (org_id = get_user_org_id());

ALTER TABLE conversion_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "conversions_org_isolation" ON conversion_events
  FOR ALL USING (org_id = get_user_org_id());

-- ─── 8. Analytics views ───────────────────────────────────────────────────────

-- Conversion attribution summary: ROAS-ready view
CREATE OR REPLACE VIEW v_conversion_attribution AS
SELECT
  c.org_id,
  c.attr_channel,
  c.attr_campaign,
  c.attr_campaign_id,
  c.attr_ad_id,
  COUNT(*)                                               AS total_conversations,
  COUNT(*) FILTER (WHERE c.outcome = 'converted')       AS conversions,
  COUNT(*) FILTER (WHERE c.outcome = 'lost')            AS lost,
  COUNT(*) FILTER (WHERE c.outcome = 'problem')         AS problems,
  SUM(c.outcome_value) FILTER (WHERE c.outcome = 'converted') AS revenue,
  AVG(c.outcome_value) FILTER (WHERE c.outcome = 'converted') AS avg_order_value,
  ROUND(
    COUNT(*) FILTER (WHERE c.outcome = 'converted')::NUMERIC
    / NULLIF(COUNT(*), 0) * 100, 1
  )                                                      AS conversion_rate_pct
FROM conversations c
WHERE c.outcome IS NOT NULL
GROUP BY c.org_id, c.attr_channel, c.attr_campaign, c.attr_campaign_id, c.attr_ad_id;

-- Top winning patterns by sector
CREATE OR REPLACE VIEW v_top_winning_patterns AS
SELECT
  ci.org_id,
  ci.sector_id,
  s.name AS sector_name,
  ci.insight_type,
  ci.title,
  ci.description,
  ci.playbook,
  ci.example_quote,
  ci.confidence,
  ci.tags,
  ci.created_at
FROM conversation_insights ci
LEFT JOIN sectors s ON s.id = ci.sector_id
WHERE ci.insight_type IN ('winning_pattern', 'key_phrase', 'objection_handled')
  AND ci.is_active = TRUE
  AND ci.confidence >= 0.7
ORDER BY ci.confidence DESC, ci.created_at DESC;
